environment:
  - matrix:
    # LTS first
    - nodejs_version: "4"
    # latest next
    - nodejs_version: "5"
    # I like 0.10 better than 0.12
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "0.8"
  - COVERALLS_REPO_TOKEN:
    secure: y+f32OuLBNyKzc39cD/5HLR9OadLIhyQBemVvIsVxZ0Po330JMfPeiABIDc1hAIO
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm config set spin false
  - npm rebuild
  - node . install -g .
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install --loglevel=http
test_script:
  - node --version
  - npm --version
  - npm test
notifications:
- provider: Slack
  incoming_webhook:
    secure: 48SDnPPTpndwEPd3ydG47Qzd9XiOmo4D9Ad77sCes/hZRsp3pT8sVy8YC+rSvK3OwgEjYCOcKTpYUrCrjlKHdPl/LnaLsWmpsJ3aUJeP9ts=
# GO_FAST
matrix:
  fast_finish: true
# we don't need the builds, we just need tests
build: off
